assessments/urls.py
from django.conf.urls import url

from . import views as v

urlpatterns = [
    url(r'^$', v.index, name='index'),
    url(r'^fill/$', v.fill, name='fill'),
    url(r'^fill/all/$', v.fill_all, name='fill_all'),
]

core/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

from . import views as v

urlpatterns = [
    url(r'^$', v.index, name='root'),
    url(r'^assessments/', include('assessments.urls', namespace='assessments')),
    url(r'^users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += [url(r'^admin/', admin.site.urls)]

users/urls.py
from django.conf.urls import url

from . import views as v

urlpatterns = [
    url(r'^login/$', v.login, name='login'),
    url(r'^logout/$', v.logout, name='logout'),
]

assessments/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

assessments/views.py
import requests

from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse

from .parser import GetListParser, BruteParser, DetailParser

# urls
base_url = 'http://ntcbadm.ntub.edu.tw/STDWEB/'
class_list_url = base_url + 'Assessment_Main.aspx'
detail_url = base_url + 'Assessment_Detail.aspx'
detail_ta_url = base_url + 'Assessment_Detail_TA.aspx'

# error message
not_time_error_message = '目前非期末教學評量時間'
login_error_message = '閒置過久或尚未登入系統，請重新登入系統!'


def index(request):
    cookies = request.session.get('cookies')
    req = requests.Session()
    res = req.get(class_list_url, cookies=cookies)
    if is_res_error(request, res):
        return redirect('users:logout')

    parser = GetListParser()
    parser.feed(res.text)

    all_class_parameter_string = ''
    for c in parser.all_class:
        if c[-1]:
            # not fill yet class
            all_class_parameter_string += c[-1] + ';'

    return render(request, 'assessments/index.html', {
        'class': parser.all_class,
        'all_class_parameter_string': all_class_parameter_string,
        'name': request.session.get('name', ''),
        'std_id': request.session.get('std_id', ''),
    })


def fill(request):
    if request.method == 'GET':
        return redirect('users:login')

    success = fill_assessments(
        request,
        request.POST.get('parametersString'),
        request.POST.get('score'),
        request.session.get('cookies'),
    )

    msg = messages.get_messages(request)
    return JsonResponse({
        'success': success,
        'messages': [m.message for m in msg]
    })


def fill_all(request):
    if request.method == 'GET':
        return redirect('users:login')

    score = request.POST.get('score')
    cookies = request.session.get('cookies')
    for parametersString in request.POST.get('parametersStrings').split(';'):
        fill_assessments(request, parametersString, score, cookies)

    msg = messages.get_messages(request)
    return JsonResponse({
        'messages': [m.message for m in msg]
    })


# functions


def is_res_error(request, res):
    flag = False
    if res.status_code != 200:
        messages.add_message(request, messages.INFO, '有些東西錯誤了，請重新嘗試')
        flag = True
    elif login_error_message in res.text:
        messages.add_message(request, messages.INFO, '登入失敗，請重新登入')
        flag = True
    elif not_time_error_message in res.text:
        messages.add_message(request, messages.INFO, '現在非教學評量填寫時間')
        flag = True

    return flag


def fill_assessments(request, parameters_string, score, cookies):
    req = requests.Session()
    res = req.get(class_list_url, cookies=cookies)
    if is_res_error(request, res):
        return False

    parameter_keys = [
        'Hide_Years',
        'Hide_Term',
        'Hide_OpClass',
        'Hide_Serial',
        'Hide_ClassShort',
        'Hide_TchNo',
        'Hide_TchName',
        'Hide_Cos_Name',
        'Hide_TermType',
        'Hide_SelStyle'
    ]
    parameter_values = parameters_string.split(',')

    parser = BruteParser()
    parser.feed(res.text)
    # parameter_values don't need last
    parser.post_data.update(dict(zip(parameter_keys, parameter_values[:-1])))

    # Decision detail url
    target_url = detail_ta_url if parameter_values[-1] == '3' else detail_url

    # Get detail page
    res = req.post(target_url, data=parser.post_data, cookies=cookies)

    parser = DetailParser()
    parser.feed(res.text)

    result = ','.join(['{}-{}-'.format(i, score)
                       for i in range(1, parser.question_count + 1)])

    parser.post_data.update({
        'SaveData': 'Y',
        'Hide_Str': result,
        'Hide_Str2': '3<|>Hello World',
    })

    res = req.post(target_url, data=parser.post_data, cookies=cookies)
    return res.status_code == 200 and res.url == class_list_url

core/views.py
from django.shortcuts import redirect


def index(request):
    return redirect('users:login')

users/views.py
import requests

from django.shortcuts import render, redirect
from django.contrib import messages

from core.parser import BruteParser

from .parser import GetNameParser


# url
login_url = 'http://ntcbadm.ntub.edu.tw/'
home_url = 'http://ntcbadm.ntub.edu.tw/Portal/indexSTD.aspx'

# error message
login_error_message = '閒置過久或尚未登入系統，請重新登入系統!'


def login(request):
    # check have login before or not
    cookies = request.session.get('cookies')
    if cookies is not None:
        res = requests.get(home_url, cookies=cookies)
        if login_error_message not in res.text:
            return redirect('assessments:index')

    if request.POST:
        req = requests.Session()
        parser = BruteParser()
        res = req.get(login_url)
        if res.status_code == 200:
            parser.feed(res.text)
            parser.post_data.update({
                'UserID': request.POST.get('username'),
                'PWD': request.POST.get('password'),
            })
            res = req.post(login_url, data=parser.post_data)
            if res.status_code == 200 and res.url == home_url:
                parser = GetNameParser()
                parser.feed(res.text)
                request.session['cookies'] = dict(req.cookies)
                request.session['std_id'] = request.POST.get('username', '')
                request.session['name'] = parser.name
                return redirect('assessments:index')

        messages.add_message(request, messages.INFO, '登入失敗，請重新嘗試')

    return render(request, 'users/login.html', {'username': request.POST.get('username', '')})


def logout(request):
    if request.session.get('cookies') is not None:
        del request.session['cookies']
        del request.session['std_id']
        del request.session['name']

    return redirect('users:login')

assessments/templates/assessments/index.html
{% extends "core/base.html" %}

{% block body %}
  <div class="row">
    <div class="col s12">
      <h3>填寫列表</h3>
      <p class="divider"></p>
    </div>
  </div>
    <div class="row">
      <div class="col m6">
        <h5>{{ std_id }} {{ name }}，你好</h5>
      </div>
      {% if all_class_parameter_string != '' %}
        <div class="col m6">
          <a class="red accent-2 waves-effect waves-light btn right" href="#modalAll">全部自動填寫</a>
          <div id="modalAll" class="modal bottom-sheet  modal-fixed-footer">
            <div class="modal-content ">
              <h4 class="center-align">分數選擇</h4>
              <p class="center-align">點擊分數以填寫</p>
              <div class="row">
                <div class="collection col s10 offset-s1 center-align">
                  <a onclick="fillAll(5)" class="collection-item">非常滿意 5</a>
                  <a onclick="fillAll(4)" class="collection-item">滿意 4</a>
                  <a onclick="fillAll(3)" class="collection-item">普通 3</a>
                  <a onclick="fillAll(2)" class="collection-item">不滿意 2</a>
                  <a onclick="fillAll(1)" class="collection-item">非常不滿意 1</a>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <a onclick="$('#modal{{ forloop.parentloop.counter }}').modal('close');" class="modal-action modal-close waves-effect waves-green btn-flat">取消</a>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
  <div class="row">
    <div class="col s12">
      <table class="centered responsive-table striped">
        <thead>
          <tr>
            <th>#</th>
            <th>開課班級</th>
            <th>科目代碼</th>
            <th>科目名稱</th>
            <th>授課教師</th>
            <th>填寫</th>
          </tr>
        </thead>
        <tbody>
          {% for c in class %}
            <tr>
              <td>{{ forloop.counter }}</td>
              {% for item in c %}
                <td>
                {% if not forloop.last %}
                  {{ item }}
                {% else %}
                  {% if item %}
                    <a class="waves-effect waves-light btn" href="#modal{{ forloop.parentloop.counter }}">自動填寫</a>
                    <div id="modal{{ forloop.parentloop.counter }}" class="modal bottom-sheet  modal-fixed-footer">
                      <div class="modal-content">
                        <h4>分數選擇</h4>
                        <p>點擊分數以填寫</p>
                        <div class="row">
                          <div class="collection col s10 offset-s1">
                            <a onclick="fill('{{ item }}', 5)" class="collection-item">非常滿意 5</a>
                            <a onclick="fill('{{ item }}', 4)" class="collection-item">滿意 4</a>
                            <a onclick="fill('{{ item }}', 3)" class="collection-item">普通 3</a>
                            <a onclick="fill('{{ item }}', 2)" class="collection-item">不滿意 2</a>
                            <a onclick="fill('{{ item }}', 1)" class="collection-item">非常不滿意 1</a>
                          </div>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <a onclick="$('#modal{{ forloop.parentloop.counter }}').modal('close');" class="modal-action modal-close waves-effect waves-green btn-flat">取消</a>
                      </div>
                    </div>
                  {% else %}
                    已填寫
                  {% endif %}
                {% endif %}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock body %}

{% block script %}
  {% csrf_token %}
  <script>
    $(document).ready(function(){
      $('.modal').modal()  // modal initial
    });

    function showLoading() {
      $('.container').html(`
        <div class="row valign-wrapper" style="height: 80vh;">
          <div class="col s10 offset-s1">
            <div class="row">
              <div class="col s12">
                <h5 class="center-align">填寫中，稍等一下～</h5>
              </div>
            </div>
            <div class="row">
              <div class="col s12">
                <div class="progress"><div class="indeterminate"></div></div>
              </div>
            </div>
          </div>
        </div>
      `)
    }

    function fill(parametersString, score) {
      var postData = {
        'csrfmiddlewaretoken': $('[name=csrfmiddlewaretoken]').val(),
        'parametersString': parametersString,
        'score': score
      }

      showLoading()

      $.post('{% url "assessments:fill" %}', postData, function (result) {
        $('.modal').modal('close')
        if (result.success) {
          window.location.reload();
        } else {
          if (result.messages[0] == '登入失敗，請重新登入') {
            window.location = '{% url "users:login" %}'
          }
          Materialize.toast(result.messages[0], 4000)
        }
      })
    }

    function fillAll(score) {
      var postData = {
        'csrfmiddlewaretoken': $('[name=csrfmiddlewaretoken]').val(),
        'parametersStrings': '{{ all_class_parameter_string }}',
        'score': score
      }

      showLoading()

      $.post('{% url "assessments:fill_all" %}', postData, function (result) {
        $('.modal').modal('close')
        for (message in result.messages) {
          if (result.messages[0] == '登入失敗，請重新登入') {
            window.location = '{% url "users:login" %}'
          }
        }
        window.location.reload();
      })
    }
  </script>
{% endblock script %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>NTUB {% block title %}Bot{% endblock title %}</title>
  <meta charset="UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% load static %}
  <link rel="stylesheet" href="{% static "css/material-icon.css" %}">
  <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
  <link rel="shortcut icon" type="image/png" href="{% static "image/logo.png" %}" />

  <style>
    .container {
      margin-top: 20px;
      margin-bottom: 40px;
    }
  </style>

  {% block style %}{% endblock style %}

  <script src="{% static "js/jquery.min.js" %}"></script>
</head>

<body>
  {% include "part/navbar.html" %}

  <div class="container">
    {% block body %}{% endblock body %}
  </div>

  <script src="{% static "js/materialize.min.js" %}"></script>

  <script>
    // log
    console.log("%c你為什麼要偷看 0.0？", "color: #f00; font-size: 50px;");

    // messages
    {% if messages %}
      {% for message in messages %}
        Materialize.toast('{{ message }}', 4000)
      {% endfor %}
    {% endif %}
  </script>

  {% block script %}{% endblock script %}
</body>

</html>

core/templates/part/navbar.html
<nav class="teal lighten-2">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">北商教評機器人</a>
    <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="#modal-about">關於</a></li>
      <li><a href="https://github.com/arthurc0102/ntubbot-django/issues/new" target="_blank">問題回報或是意見</a></li>
      {% if request.path != '/users/login/' %}
        <li><a href="{% url 'users:logout' %}">登出</a></li>
      {% endif %}
    </ul>
    <ul class="side-nav" id="mobile">
      <li><a href="#modal-about" onclick="$('#mobile').sideNav('hide');">關於</a></li>
      <li><a href="https://github.com/arthurc0102/ntubbot-django/issues/new" onclick="$('#mobile').sideNav('hide');" target="_blank">問題回報或是意見</a></li>
      {% if request.path != '/users/login/' %}
        <li><a href="{% url 'users:logout' %}">登出</a></li>
      {% endif %}
    </ul>
  </div>
</nav>

<div id="modal-about" class="modal">
  <div class="modal-content">
    <h4>關於</h4>
    <p class="divider"></p>
    <p>
      這是北商大的教學評量機器人<br />
      建議由機器人填寫完畢後到<a href="http://ntcbadm.ntub.edu.tw/" target="_blank">系統</a>中確認<br />
      這個專案是開源的<a href="https://github.com/arthurc0102/ntubbot" target="_blank">點這邊</a>查看
    </p>
    <p>
      我是<a href="http://arthurc.me" target="_blank">拉布</a>，徵求想一起維護的人，用 Email (arthurc0102@gmail.com) 聯絡我或發<a href="https://www.facebook.com/arthurc0102" target="_blank">臉書</a>訊息給我～
    </p>
  </div>
</div>


<script>
  // for navbar
  $( document ).ready(function(){
    $(".button-collapse").sideNav();
    $('.modal').modal()  // modal initial
  })
</script>

<style>
  /* for nav */
  .nav-wrapper {
    padding-right: 10px;
  }

  .brand-logo {
    margin-left: 10px;
  }
</style>

users/templates/users/login.html
{% extends "core/base.html" %}

{% block style %}
  <style>
    .submit-btn {
      margin-right: 10px;
    }
  </style>
{% endblock style %}

{% block body %}
  <div class="row">
    <div class="col s10 offset-s1 m6 offset-m3">
      <h3>登入</h3>
      <p class="divider"></p>
    </div>
  </div>
  <div class="row">
    <form class="col s10 offset-s1 m6 offset-m3" action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s12">
          <input id="id_username" name="username" type="text" class="validate" value="{{ username }}" required>
          <label for="id_username">北商資訊系統帳號 (學號)</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="id_password" name="password" type="password" class="validate" required>
          <label for="id_password">北商資訊系統密碼</label>
        </div>
      </div>
      <div class="row">
        <button class="btn waves-effect waves-light right submit-btn" type="submit">Login
          <i class="material-icons right">send</i>
        </button>
      </div>
    </form>
  </div>
{% endblock body %}